### ISSUE TITLE
make bench-all throwing Error 101

### ISSUE THREAD

**Issue by infinitron** [brave-experiments/frodo-pir#4]
Hi there,

I'm trying to run the command `make bench-all` and it's throwing the following error.
```bash
RUST_BACKTRACE=1 DB_FILE=../data/rand_db.json PARAMS_OUTPUT_PATH=../data/params.json PIR_LWE_DIM=1572 PIR_ELE_SIZE_EXP=13 PIR_NUM_SHARDS=8 PIR_MATRIX_HEIGHT_EXP=16 PIR_PLAINTEXT_BITS=10 cargo bench > benchmarks-16.txt
    Finished bench [optimized] target(s) in 0.04s
     Running unittests src/lib.rs (target/release/deps/frodo_pir-9012b63c534b7f50)
     Running benches/bench.rs (target/release/deps/bench-3b871c51064bfde6)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorQueryParamsReused', benches/bench.rs:114:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: criterion::bencher::Bencher<M>::iter
   4: <criterion::routine::Function<M,F,T> as criterion::routine::Routine<M,T>>::warm_up
   5: criterion::routine::Routine::sample
   6: criterion::analysis::common
   7: criterion::benchmark_group::BenchmarkGroup<M>::bench_function
   8: bench::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: bench failed
make: *** [Makefile:56: bench-all] Error 101
```
Can you please help me with this?
(I'm running Ubuntu 22.04 with the latest version of Docker)

**Comment by claucece** [comment]
It should be fixed now ;)

Thanks!
